import {PlantsModel} from './models/plantsModel';

export const plantTestData: PlantsModel[] = [
  {latin_name: 'Acacia baileyana \'Purpurea\'',
    common_name: 'Purple-Leaf Acacia',
    family_name: 'Fabaceae',
    plant_type: 'Tree (evergreen)',
    bloom_time: 'Spring',
    flower_color: 'Yellow',
    size_at_maturity: '> 24 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun',
    water_needs: 'Low',
    associated_wildlife: 'Birds;Butterflies',
    stormwater_benefit: 'No',
    stormwater_int: '0',
    appropriate_location: 'Sidewalk',
    suggested_green_connection_routes: 'NA',
    street_tree_list: '2 (B)',
    additional_characteristices_notes: 'Fast grower, high maintenance.',
    photocredit01: ' ',
    photocredit02: ' ',
    photocredit03: ' ',
    photocredit04: ' ',
    habitat: 'Yes',
    habitat_int: '1',
    sidewalk_landscaping_plants: 'Yes',
    sidewalk_landscaping_plants_int: '1'}, {latin_name: 'Acacia baileyana \'Purpurea\'',
    common_name: 'Purple-Leaf Acacia',
    family_name: 'Fabaceae',
    plant_type: 'Tree (evergreen)',
    bloom_time: 'Spring',
    flower_color: 'Yellow',
    size_at_maturity: '> 24 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun',
    water_needs: 'Low',
    associated_wildlife: 'Birds;Butterflies',
    stormwater_benefit: 'No',
    stormwater_int: '0',
    appropriate_location: 'Sidewalk',
    suggested_green_connection_routes: 'NA',
    street_tree_list: '2 (B)',
    additional_characteristices_notes: 'Fast grower, high maintenance.',
    photocredit01: '',
    photocredit02: '',
    photocredit03: ',',
    photocredit04: ',',
    habitat: 'Yes',
    habitat_int: '1',
    sidewalk_landscaping_plants: 'Yes',
    sidewalk_landscaping_plants_int: '1'}
];
