import {PlantsModel} from './models/plantsModel';

export const plantTestData: PlantsModel[] = [
  {
    latin_name: 'Acacia baileyana \'Purpurea\'',
    common_name: 'Purple-Leaf Acacia',
    family_name: 'Fabaceae',
    plant_type: 'Tree (evergreen)',
    bloom_time: 'Spring',
    flower_color: 'Yellow',
    size_at_maturity: '> 24 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun',
    water_needs: 'Low',
    associated_wildlife: 'Birds;Butterflies',
    stormwater_benefit: 'No',
    stormwater_int: '0',
    appropriate_location: 'Sidewalk',
    suggested_green_connection_routes: 'NA',
    street_tree_list: '2 (B)',
    additional_characteristices_notes: 'Fast grower, high maintenance.',
    photocredit01: ' ',
    photocredit02: ' ',
    photocredit03: ' ',
    photocredit04: ' ',
    habitat: 'Yes',
    habitat_int: '1',
    sidewalk_landscaping_plants: 'Yes',
    sidewalk_landscaping_plants_int: '1'
  }, {
    latin_name: 'Acacia baileyana \'Purpurea\'',
    common_name: 'Purple-Leaf Acacia',
    family_name: 'Fabaceae',
    plant_type: 'Tree (evergreen)',
    bloom_time: 'Spring',
    flower_color: 'Yellow',
    size_at_maturity: '> 24 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun',
    water_needs: 'Low',
    associated_wildlife: 'Birds;Butterflies',
    stormwater_benefit: 'No',
    stormwater_int: '0',
    appropriate_location: 'Sidewalk',
    suggested_green_connection_routes: 'NA',
    street_tree_list: '2 (B)',
    additional_characteristices_notes: 'Fast grower, high maintenance.',
    photocredit01: '',
    photocredit02: '',
    photocredit03: ',',
    photocredit04: ',',
    habitat: 'Yes',
    habitat_int: '1',
    sidewalk_landscaping_plants: 'Yes',
    sidewalk_landscaping_plants_int: '1'
  }
];

export const filterTestData: PlantsModel[] = [
  {
    latin_name: 'Helianthus \'Lemon Queen\'',
    common_name: 'Lemon Queen',
    family_name: 'Asteraceae',
    plant_type: 'Perennial',
    bloom_time: 'Summer',
    flower_color: 'Yellow',
    size_at_maturity: '1-3 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun',
    soil_type: 'Clay',
    water_needs: 'Low',
    habitat_value: 'Pollinator',
    associated_wildlife: 'hummingbirds;Butterflies;bees',
    appropriate_location: 'Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©2007 underwaterer',
    photocredit02: '©2009 Klasse Im Garten\n2009 Klasse Im Garten',
    habitat: 'Yes',
    habitat_int: '1'
  },
  {
    latin_name: 'Teucrium x lucidrys',
    common_name: 'Wall Germander',
    family_name: 'Lamiaceae',
    former_latin_name: 'Teucrium chamaedrys',
    plant_type: 'Perennial',
    bloom_time: 'Summer',
    flower_color: 'Magenta',
    size_at_maturity: '1-3 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun',
    soil_type: 'Clay;Loam;Sand;Rock',
    water_needs: 'None',
    habitat_value: 'Pollinator',
    associated_wildlife: 'Butterflies;bees',
    appropriate_location: 'Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©2015 Enbodenumer\n2015 Enbodenumer\n2015 Enbodenumer',
    photocredit02: '©2015 Enbodenumer\n2015 Enbodenumer\n2015 Enbodenumer',
    habitat: 'Yes',
    habitat_int: '1'
  },
  {
    latin_name: 'Macfadyena unguis-cati',
    common_name: 'Yellow Trumpet Vine',
    family_name: 'Bignoniaceae',
    plant_type: 'Vine',
    bloom_time: 'Summer',
    flower_color: 'Yellow',
    size_at_maturity: '> 24 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun;Part Shade',
    habitat_value: 'Cover;Nesting',
    appropriate_location: 'Sidewalk;Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©1998 Forest and Kim Starr',
    photocredit02: '©2006 Forest and Kim Starr\n2006 Forest and Kim Starr\n2006 Forest and Kim Starr',
    sidewalk_landscaping_plants: 'Yes',
    sidewalk_landscaping_plants_int: '1'
  },
  {
    latin_name: 'Miscanthus sinensis',
    common_name: '\tJapanese silver grass',
    family_name: 'Poaceae',
    plant_type: 'Grass',
    bloom_time: 'Summer',
    size_at_maturity: '1-3 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun',
    soil_type: 'Clay;Loam;Sand',
    water_needs: 'Moderate',
    stormwater_benefit: 'Yes',
    stormwater_int: '1',
    appropriate_location: 'Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©Nick Kurzenko',
    photocredit02: '©Nick Kurzenko \nNick Kurzenko'
  },
  {
    latin_name: 'Calamagrostis x acutiflora',
    common_name: 'Feather Reed Grass',
    family_name: 'Poaceae',
    plant_type: 'Grass',
    bloom_time: 'Summer',
    flower_color: 'Purple',
    size_at_maturity: '4-6 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun;Part shade',
    water_needs: 'Low',
    appropriate_location: 'Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©2009 Daryl Mitchell',
    photocredit02: '©2008 Patrick Standish\n2008 Patrick Standish',
    thrifty150: 'Yes',
    thrifty150_int: '1'
  },

  {
    latin_name: 'Cerastium tomentosum',
    common_name: 'Snow-in-Summer',
    family_name: 'Caryophyllaceae',
    plant_type: 'Perennial',
    bloom_time: 'Summer',
    flower_color: 'White',
    size_at_maturity: '< 1 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun;Part Shade',
    soil_type: 'Sand;Rock;Loam',
    water_needs: 'None',
    appropriate_location: 'Sidewalk;Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©2016 Stefano',
    photocredit02: '©2010 Phil Sellens\n2010 Phil Sellens',
    sidewalk_landscaping_plants: 'Yes',
    sidewalk_landscaping_plants_int: '1'
  },
  {
    latin_name: 'Festuca muelleri',
    common_name: 'Mueller\'s Fescue',
    family_name: 'Poaceae',
    plant_type: 'Grass',
    bloom_time: 'Summer',
    flower_color: 'Brown',
    size_at_maturity: '< 1 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun;Part Shade',
    appropriate_location: 'Sidewalk;Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: 'www.smgrowers.com',
    photocredit02: '©2015 Russel Best\n2015 Russell Best \n2015 Russell Best',
    sidewalk_landscaping_plants: 'Yes',
    sidewalk_landscaping_plants_int: '1'
  },
  {
    latin_name: 'Tanacetum haradjanii',
    common_name: 'Silver Tansy',
    family_name: 'Asteraceae',
    plant_type: 'Perennial',
    bloom_time: 'Summer',
    flower_color: 'Yellow',
    size_at_maturity: '< 1 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun',
    soil_type: 'Sand;Loam;Clay',
    water_needs: 'Low',
    appropriate_location: 'Sidewalk;Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©2007 Dusanima',
    photocredit02: '©2008 Klasse Im Garten\n2008 Klasse Im Garten',
    sidewalk_landscaping_plants: 'Yes',
    sidewalk_landscaping_plants_int: '1'
  },
  {
    latin_name: 'Thymus \'Victor Reiter\'',
    common_name: 'Victor Reiter Thyme',
    family_name: 'Lamiaceae',
    plant_type: 'Perennial',
    bloom_time: 'Summer',
    flower_color: 'Pink',
    size_at_maturity: '< 1 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun;Part Shade',
    soil_type: 'Sand;Loam',
    water_needs: 'None',
    habitat_value: 'Pollinator',
    associated_wildlife: 'Bees',
    appropriate_location: 'Sidewalk;Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©2014 Andreas Rockstein\n2014 Andreas Rockstein\n2014 Andreas Rockstein',
    habitat: 'Yes',
    habitat_int: '1',
    sidewalk_landscaping_plants: 'Yes',
    sidewalk_landscaping_plants_int: '1'
  },
  {
    latin_name: 'Lychnis coronaria            ',
    common_name: 'Rose Campion',
    family_name: 'Caryophyllaceae',
    plant_type: 'Perennial',
    bloom_time: 'Summer',
    flower_color: 'Magenta',
    size_at_maturity: '1-3 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun;Part shade',
    soil_type: 'Clay;Sand;Loam;Rock',
    water_needs: 'Low',
    appropriate_location: 'Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©2011 Stefano',
    photocredit02: '©2008 Pony Lauricella\n2008 Pony Lauricella',
    thrifty150: 'Yes',
    thrifty150_int: '1'
  },
  {
    latin_name: 'Diospyros virginiana',
    common_name: 'persimmon',
    family_name: 'Ebenaceae',
    plant_type: 'Tree (deciduous)',
    bloom_time: 'Summer',
    flower_color: 'Yellow',
    size_at_maturity: '> 24 ft',
    climate_appropriate_plants: 'Exotic',
    suitable_site_conditions: 'Sun;Part Shade;Shade',
    soil_type: 'Clay;Loam;sand',
    water_needs: 'Low',
    habitat_value: 'Fruit;Cover;Nesting',
    stormwater_benefit: 'Yes',
    stormwater_int: '1',
    appropriate_location: 'Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©2007 Scott Zona',
    photocredit02: '© 2015 Will Pollard\n2015 Will Pollard  \n2015 Will Pollard'
  },
  {
    latin_name: 'Nolina bigelovii',
    common_name: 'Bear Grass',
    family_name: 'Ruscaceae',
    plant_type: 'Shrub (evergreen)',
    bloom_time: 'Summer',
    size_at_maturity: '4-6 ft',
    climate_appropriate_plants: 'CA Native',
    suitable_site_conditions: 'Sun',
    soil_type: 'Sand;Loam',
    water_needs: 'None',
    appropriate_location: 'Garden',
    suggested_green_connection_routes: 'NA',
    street_tree_list: 'NA',
    photocredit01: '©2013 Lon&Queta\n2013 Lon&Queta',
    photocredit02: '©2006Larry Hogue',
    habitat: 'Yes',
    habitat_int: '1',
    thrifty150: 'Yes',
    thrifty150_int: '1'
  },
];
